### ISSUE TITLE
css15.实现元素的水平垂直居中

### ISSUE THREAD

**Issue by lixiaojuan12** [lixiaojuan12/Summary-of-interview-questions#15]
**文字水平垂直居中：**
- text-align: center;  水平
- height = line-height  垂直
```css
div {
    width: 100px;
    height: 100px;
    line-height: 100px;
    background-color: crimson;
    text-align: center;
}
<div>
    123
</div>
```
**块级元素水平垂直**

方法一：
- 父元素： position：relative【任意一种定位】
- 子元素：position:absolute;四个方向为0.margin：auto
```css
.outer {
    position: relative;
    width: 100px;
    height: 100px;
    background-color: crimson;
}

.inner {
    position: absolute;
    top: 0;
    right: 0;
    bottom: 0;
    left: 0;
    margin: auto;
    width: 50px;
    height: 50px;
    background-color: darkblue;
}
<div class='outer'>
     <div class="inner"></div>
</div>
```
方法二：
- 父元素： position：relative【任意一种定位】
- 子元素：position:absolute;top: 50%;left: 50%; transform: translate(-50%, -50%);
```css
.outer {
    position: relative;
    width: 100px;
    height: 100px;
    background-color: crimson;
}

.inner {
    position: absolute;
    top: 50%;
    left: 50%;
    transform: translate(-50%, -50%);
    width: 50px;
    height: 50px;
    background-color: darkcyan;
}
<div class="outer">
     <div class="inner">
     </div>
</div>
```
方法三：
- 父元素：flex布局
- 子元素：margin:auto
```css
.outer {
    width: 100px;
    height: 100px;
    background-color: crimson;
    display: flex;
}

.inner {
    width: 50px;
    height: 50px;
    background-color: darkgoldenrod;
    margin: auto;
}
<div class="outer">
    <div class="inner"></div>
</div>
```
方法很多，欢迎大家在下方评论多出一块学习🤝
