### ISSUE TITLE
css7. 浮动问题

### ISSUE THREAD

**Issue by lixiaojuan12** [lixiaojuan12/Summary-of-interview-questions#7]
**浮动的取值**
- 该属性的值指出了对象是否及如何浮动；
- `float:left`; 左浮动
- `float:right`;右浮动
- `float:none`; (默认的，没有浮动)

**浮动的特点**
- 脱离正常文档流（不占位置）
- 左浮动，右浮动的方向针对的是父级
- 可以让元素排列到一行显示；
- `float:left`左浮动是靠左显示; `float:right `右浮动是靠右显示；
- 同时设置左浮动，元素是按照html结构的顺序从左往右依次排列；
- 同时设置右浮动，元素与html结构的顺序相反，从右往左依次排列；如果想要正常html结构顺序，用右浮动就需要把html结构调换位置即可；
- 浮动不会继承也不会传递；
- 正常文档流中，宽度是可继承的，但是一旦浮动，宽度不能再继承父级的，而是由自身内容大小决定。
- 行内元素本来写宽、高是不起作用的，但是一旦设置浮动，设置宽、高也可以起作用。
- 浮动的本质：最初的时候是为了实现图文混排，场景：有一张图片，一些文字，如果给图片设置浮动，文字就会环绕图片进行排列

**浮动的影响**
- 会导致父元素的高度失效 值为0，后面的元素识别不了它的高度，就会往前占领它的位置；
- 给父元素设置背景颜色不起作用
- 给父元素设置边框属性不会被撑开
- 给父元素设置内边距`padding `不会被撑开

**浮动的天然克星clear**

clear属性官方解释：元素盒子的边不能和前面的浮动元素相邻；
- `clear: none` 默认值，左右浮动来就来；
- `clear: left` 左侧抗浮动；
- `clear: right` 右侧抗浮动；
- `clear: both `两侧抗浮动；
- `clear`属性只有块级元素才有效的；而`::after`等伪元素默认都是内联水平，这就是借助伪元素清除浮动影响时需要设置`display`属性值的原因；
```css
.clear:after{
    content:'';
    display:table; // 也可以是"block"或者"list-item"
    clear:both;
}
```
**浮动造成的父级”盒子塌陷”问题如何解决**
- 直接给浮动元素的父级增加`height`
- 给浮动元素的父级增加`overflow:hidden`;(超出隐藏)
- 给浮动元素父级的末尾增加一个元素，给这个元素设置`clear：both;`样式
- 在项目中，直接把下面的`clearfix`样式粘贴到你的css中，哪个元素浮动，就给赶紧给父级增加clearfix这个类名。（它的本质和第三种方法是一样的）
```css
// 最完整clearfix清除浮动的方法：
.clearfix:after{
    content:'';
    display:block;
    clear:both;
    width:0;
    height:0;
    line-height:0;
    font-size:0;
    visibility: hidden;
    overflow:hidden;
}
.clearfix{
    zoom:1;
}
```
